CREATE TABLE PRO_PROCESO (
  PRO_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  PRO_NOMBRE VARCHAR(15) NOT NULL,
  PRO_PREFIJO VARCHAR(3) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO PRO_PROCESO (PRO_ID, PRO_NOMBRE, PRO_PREFIJO) VALUES ('1', 'INGENERIA', 'ING');
INSERT INTO PRO_PROCESO (PRO_ID, PRO_NOMBRE, PRO_PREFIJO) VALUES ('2', 'LICENCIADO', 'LIC');
INSERT INTO PRO_PROCESO (PRO_ID, PRO_NOMBRE, PRO_PREFIJO) VALUES ('3', 'ABOGADO', 'ABG');
INSERT INTO PRO_PROCESO (PRO_ID, PRO_NOMBRE, PRO_PREFIJO) VALUES ('4', 'DOCTOR', 'DR');
INSERT INTO PRO_PROCESO (PRO_ID, PRO_NOMBRE, PRO_PREFIJO) VALUES ('5', 'GERENTE', 'GTE');

CREATE TABLE TIP_TIPO_DOC (
  TIP_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  TIP_NOMBRE VARCHAR(15) NOT NULL,
  TIP_PREFIJO VARCHAR(3) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO TIP_TIPO_DOC (TIP_ID, TIP_NOMBRE, TIP_PREFIJO) VALUES ('1', 'INSTRUCTIVO', 'INS');
INSERT INTO TIP_TIPO_DOC (TIP_ID, TIP_NOMBRE, TIP_PREFIJO) VALUES ('2', 'LIBRO', 'LIB');
INSERT INTO TIP_TIPO_DOC (TIP_ID, TIP_NOMBRE, TIP_PREFIJO) VALUES ('3', 'ARTICULO', 'ART');
INSERT INTO TIP_TIPO_DOC (TIP_ID, TIP_NOMBRE, TIP_PREFIJO) VALUES ('4', 'FOLIO', 'FOL');
INSERT INTO TIP_TIPO_DOC (TIP_ID, TIP_NOMBRE, TIP_PREFIJO) VALUES ('5', 'REGISTRO', 'REG');

CREATE TABLE DOC_DOCUMENTO (
  DOC_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  DOC_NOMBRE VARCHAR(155) NOT NULL,
  DOC_CODIGO VARCHAR(20) UNIQUE NOT NULL,
  DOC_CONTENIDO TEXT NOT NULL,
  DOC_ID_TIPO BIGINT UNSIGNED NOT NULL,
  DOC_ID_PROCESO BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  FOREIGN KEY (DOC_ID_TIPO) REFERENCES TIP_TIPO_DOC(TIP_ID),
  FOREIGN KEY (DOC_ID_PROCESO) REFERENCES PRO_PROCESO(PRO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
